### ISSUE TITLE
unable to work on centos 7.7

### ISSUE THREAD

**Issue by proximitus** [naworkcaj/betrayed#3]
CentOS Linux release 7.7.1908 (Core)

tried `./install.sh us.undernet.org mychannel` didn't worked
tried `./install.sh IP mychannel` didn't worked
set `FORK_IMMEDIATELY = 0` then manually input `cat /dev/null` didn't worked

**Comment by naworkcaj** [comment]
You need to include the hash in the channel name. Surrounded with single quotation marks.
As you posted, to install you would run `./install.sh us.undernet.org '#mychannel'`
